name: aptos
description: Aptos Dart SDK.
version: 0.0.3
repository: https://github.com/0xmove/aptos

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  dio: ^4.0.6
  hex: ^0.2.0
  ed25519_edwards: ^0.3.1
  pointycastle: ^3.6.2
  bip39: ^1.0.6
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0